# Aula 3: Matrizes e introdução a dados

## Numpy
Arrays e matrizes.

### Criando Arrays

In [1]:
import numpy as np

Criando arrays a partir de listas.

In [2]:
lista_1 = [1, 2, 3, 4, 5]

In [3]:
lista_2 = [10, 11, 12, 13, 14]

In [4]:
np_array_1 = np.array(lista_1)

In [5]:
np_array_1

array([1, 2, 3, 4, 5])

In [6]:
np_array_1.shape

(5,)

In [7]:
np_array_1.dtype

dtype('int64')

In [8]:
lista_3 = [lista_1, lista_2]

In [9]:
lista_3

[[1, 2, 3, 4, 5], [10, 11, 12, 13, 14]]

In [10]:
np_array_2 = np.array(lista_3)

In [11]:
np_array_2

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [12]:
np_array_2.shape

(2, 5)

In [13]:
np_array_2.dtype

dtype('int64')

Criando arrays a partir de estruturas pré-definidas.

In [14]:
matriz_zeros = np.zeros(10)

In [15]:
matriz_zeros

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [16]:
matriz_zeros_2 = np.zeros([4, 2])

In [17]:
matriz_zeros_2

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [18]:
matriz_uns_1 = np.ones([2,3])

In [19]:
matriz_uns_1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
matriz_vazia = np.empty([2, 3])

In [21]:
matriz_vazia

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Matriz identidade

In [22]:
matriz_id = np.eye(5)

In [23]:
matriz_id

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [24]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

Sintaxe, primeiro parâmetro o início, depois o fim e por último o passo.

In [25]:
np.arange(10, 20, 4)

array([10, 14, 18])

In [26]:
np.arange(1, 5)

array([1, 2, 3, 4])

### Escalares

In [27]:
array_1 = np.array([[10, 20, 30, 40], [1, 2, 3, 4]])
array_2 = np.array([[50, 60, 70, 80],[5, 6, 7, 8]])

In [28]:
array_1 * array_2

array([[ 500, 1200, 2100, 3200],
       [   5,   12,   21,   32]])

In [29]:
array_1 + array_2

array([[ 60,  80, 100, 120],
       [  6,   8,  10,  12]])

In [30]:
array_1 - array_2

array([[-40, -40, -40, -40],
       [ -4,  -4,  -4,  -4]])

In [31]:
array_1**(0.5)

array([[ 3.16227766,  4.47213595,  5.47722558,  6.32455532],
       [ 1.        ,  1.41421356,  1.73205081,  2.        ]])

In [32]:
1 / array_2

array([[ 0.02      ,  0.01666667,  0.01428571,  0.0125    ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

### Índices

In [33]:
array = np.arange(0, 11)

In [34]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
array[2]

2

Retorna a lista do índice 1, os arrays sempre começam com o índice 0, até o índice 5.

In [36]:
array[1:6]

array([1, 2, 3, 4, 5])

In [37]:
array[:4]

array([0, 1, 2, 3])

Definindo valores por índice

In [38]:
array[1:6] = 99

In [39]:
array

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Referências em memórias, cuidado

In [40]:
slice_array = array[6:]

In [41]:
slice_array

array([ 6,  7,  8,  9, 10])

In [42]:
slice_array[:] = 100

In [43]:
slice_array

array([100, 100, 100, 100, 100])

In [44]:
array

array([  0,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100])

O slice_array estava com a referência em memória de array, mesmo que para uma parte parcial do array.

Para evitar operações como esta, utilizar o comando copy.

In [45]:
array_copy = array.copy()

In [46]:
array_copy[:] = 99

In [47]:
array_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [48]:
array

array([  0,  99,  99,  99,  99,  99, 100, 100, 100, 100, 100])

In [49]:
array_2d = np.array(([1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]))

In [50]:
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [51]:
array_2d[1]

array([ 6,  7,  8,  9, 10])

In [52]:
array_2d[1][0]

6

Obter todos as linhas até a segunda

In [53]:
array_2d[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Obter todas as linhas até a segunda e a partir do segundo item

In [54]:
array_2d[:2, 1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

### Transposition

In [55]:
matriz = np.arange(20).reshape((4,5))

In [56]:
matriz

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
matriz.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [58]:
np.dot(matriz.T, matriz)

array([[350, 380, 410, 440, 470],
       [380, 414, 448, 482, 516],
       [410, 448, 486, 524, 562],
       [440, 482, 524, 566, 608],
       [470, 516, 562, 608, 654]])

In [59]:
matriz_3d = np.arange(48).reshape((4,4,3))

In [60]:
matriz_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47]]])

In [61]:
matriz_3d.T

array([[[ 0, 12, 24, 36],
        [ 3, 15, 27, 39],
        [ 6, 18, 30, 42],
        [ 9, 21, 33, 45]],

       [[ 1, 13, 25, 37],
        [ 4, 16, 28, 40],
        [ 7, 19, 31, 43],
        [10, 22, 34, 46]],

       [[ 2, 14, 26, 38],
        [ 5, 17, 29, 41],
        [ 8, 20, 32, 44],
        [11, 23, 35, 47]]])

In [62]:
array = np.array([[1,2,3,4]])

In [63]:
array

array([[1, 2, 3, 4]])

In [64]:
array.swapaxes(1,0)

array([[1],
       [2],
       [3],
       [4]])

In [65]:
array.swapaxes(1,1)

array([[1, 2, 3, 4]])

### Funções Universais

In [66]:
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
np.sqrt(array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [68]:
np.exp(array)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [69]:
array_random_1 = np.random.randn(4)
array_random_1

array([ 1.68002653,  1.43948965,  0.65536166,  0.0313949 ])

In [70]:
array_random_2 = np.random.randn(4)
array_random_2

array([ 0.58521877, -0.30020927,  1.03044609,  0.21939818])

### Funções Universais Binárias

In [71]:
np.add(array_random_1, array_random_2)

array([ 2.26524529,  1.13928037,  1.68580776,  0.25079309])

In [72]:
np.maximum(array_random_1, array_random_2)

array([ 1.68002653,  1.43948965,  1.03044609,  0.21939818])

### Operações com Arrays

Utilizando o where.

In [81]:
array_1 = np.array([1, 2, 3, 4, 5, 6])
array_2 = np.array([31, 32, 33, 34, 35, 36])

In [82]:
condicao = np.array([True, False, True, False, True, False])
array_3 = np.where(condicao, array_1, array_2)
array_3

array([ 1, 32,  3, 34,  5, 36])

In [83]:
array = np.random.randn(5,5)
array

array([[-1.92406459, -1.7694122 , -0.09220327,  0.09137074, -0.4697482 ],
       [-0.45326096, -0.49851914,  0.21828408,  0.04695309, -0.89611429],
       [-1.62577892,  0.14696145,  0.68054414, -0.35087121, -0.50453517],
       [-0.00273631,  1.07461361, -0.22354422,  0.96206418,  1.4241114 ],
       [-0.50574148,  0.10605682, -0.51225597,  0.59693651,  0.87595544]])

In [84]:
np.where(array<0, 0, array)

array([[ 0.        ,  0.        ,  0.        ,  0.09137074,  0.        ],
       [ 0.        ,  0.        ,  0.21828408,  0.04695309,  0.        ],
       [ 0.        ,  0.14696145,  0.68054414,  0.        ,  0.        ],
       [ 0.        ,  1.07461361,  0.        ,  0.96206418,  1.4241114 ],
       [ 0.        ,  0.10605682,  0.        ,  0.59693651,  0.87595544]])

In [85]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
array.sum()

45

Soma verticalmente.

In [87]:
    array.sum(0)

array([12, 15, 18])

Soma horizontalmente.

In [88]:
array.sum(1)

array([ 6, 15, 24])

In [89]:
array.shape

(3, 3)

In [90]:
array.mean()

5.0

In [91]:
array.std()

2.5819888974716112

In [92]:
array_boolean = np.array([True, True, False, True, True])

In [93]:
array_boolean.any()

True

In [94]:
array_boolean.all()

False

In [95]:
array = np.random.randn(8)
array

array([ 0.89033759,  0.60129859,  0.0041177 ,  0.03205817,  0.47807382,
        0.51011451, -0.0821951 ,  0.46976538])

In [96]:
array.sort()
array

array([-0.0821951 ,  0.0041177 ,  0.03205817,  0.46976538,  0.47807382,
        0.51011451,  0.60129859,  0.89033759])

In [97]:
nomes = np.array(["José", "Alice", "Beatriz", "Zacarias", "Yves", "Xavantes", "Yves"])

In [98]:
np.unique(nomes)

array(['Alice', 'Beatriz', 'José', 'Xavantes', 'Yves', 'Zacarias'], 
      dtype='<U8')

In [99]:
np.in1d(["Alice", "José"], nomes)

array([ True,  True], dtype=bool)

### Input & Output

In [100]:
array_1 = np.arange(8)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [101]:
np.save("array", array_1)

In [102]:
np.load("array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7])

In [103]:
array_2 = np.arange(10)
array_3 = np.arange(8)

In [104]:
np.savez("array.npz", x=array_2, y=array_3, outro=array_1)

In [105]:
archive_arrays = np.load("array.npz")

In [106]:
archive_arrays["outro"]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [107]:
archive_arrays["x"], archive_arrays["y"]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7]))

In [108]:
np.savetxt("array.txt", array_1, delimiter=";")

In [109]:
np.loadtxt("array.txt", delimiter=";")

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

## Pandas
Estruturas de dados para acesso a fontes de informações e manipulações

### Series

In [110]:
import pandas as pd
from pandas import Series, DataFrame

In [111]:
serie = Series([1,2,3,4,5,6])
serie

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [112]:
serie.values

array([1, 2, 3, 4, 5, 6])

In [113]:
serie.index

RangeIndex(start=0, stop=6, step=1)

In [114]:
pib_paises = Series([10000000, 8000000, 7000000, 6000000, 5000000], index = ["China", "Estados Unidos", "Canadá", "Rússia", "Brasil"] )
pib_paises

China             10000000
Estados Unidos     8000000
Canadá             7000000
Rússia             6000000
Brasil             5000000
dtype: int64

In [115]:
pib_paises["Brasil"]

5000000

In [116]:
pib_paises[pib_paises > 7000000]

China             10000000
Estados Unidos     8000000
dtype: int64

In [117]:
"Argentina" in pib_paises

False

Conversão para dicionário

In [118]:
pib_paises_dict = pib_paises.to_dict()
pib_paises_dict

{'Brasil': 5000000,
 'Canadá': 7000000,
 'China': 10000000,
 'Estados Unidos': 8000000,
 'Rússia': 6000000}

In [119]:
lista_paises = ["China", "Estados Unidos", "Canadá", "Rússia", "Brasil", "Peru"]

In [120]:
serie_2 = Series(pib_paises_dict, index = lista_paises)
serie_2

China             10000000.0
Estados Unidos     8000000.0
Canadá             7000000.0
Rússia             6000000.0
Brasil             5000000.0
Peru                     NaN
dtype: float64

Nulo em estruturas de dados recebe o valor NaN, Not a Natural.

In [121]:
pd.isnull(serie_2)

China             False
Estados Unidos    False
Canadá            False
Rússia            False
Brasil            False
Peru               True
dtype: bool

In [122]:
pd.notnull(serie_2)

China              True
Estados Unidos     True
Canadá             True
Rússia             True
Brasil             True
Peru              False
dtype: bool

In [123]:
pib_paises + serie_2

Brasil            10000000.0
Canadá            14000000.0
China             20000000.0
Estados Unidos    16000000.0
Peru                     NaN
Rússia            12000000.0
dtype: float64

In [124]:
serie_2.name="Produto interno bruto"
serie_2.index.name="País"
serie_2

País
China             10000000.0
Estados Unidos     8000000.0
Canadá             7000000.0
Rússia             6000000.0
Brasil             5000000.0
Peru                     NaN
Name: Produto interno bruto, dtype: float64

### Dataframes

Carregar o arquivo de dados da quarta temporada do seriado Breaking Bad, no formato CSV.

In [129]:
breaking_bad_temporada_4 = pd.read_csv("breaking_bad_4_temp.csv", delimiter=";")
breaking_bad_temporada_4

Nº  Nº.1             Título      Dirigido por:  \
0   34     1         Box Cutter     Adam Bernstein   
1   35     2  Thirty-Eight Snub  Michelle MacLaren   
2   36     3         Open House        David Slade   
3   37     4      Bullet Points      Colin Bucksey   
4   38     5            Shotgun  Michelle MacLaren   
5   39     6           Cornered     Michael Slovis   
6   40     7        Problem Dog        Peter Gould   
7   41     8           Hermanos        Johan Renck   
8   42     9                Bug    Terry McDonough   
9   43    10              Salud  Michelle MacLaren   
10  44    11        Crawl Space       Scott Winant   
11  45    12          End Times     Vince Gilligan   
12  46    13           Face Off     Vince Gilligan   

                             Escrito por: Audiência       Exibição Original  
0                          Vince Gilligan  2.58[38]     17 de julho de 2011  
1                          George Mastras  1.97[39]     24 de julho de 2011  
2                              Sam Catlin  1.71[40]     31 de julho de 2011  
3                    Moira Walley-Beckett  1.83[41]     7 de agosto de 2011  
4                          Thomas Schnauz  1.75[42]    14 de agosto de 2011  
5                      Gennifer Hutchison  1.67[43]    21 de agosto de 2011  
6                             Peter Gould  1.91[44]    28 de agosto de 2011  
7             Sam Catlin & George Mastras  1.98[45]   4 de setembro de 2011  
8   Moira Walley-Beckett & Thomas Schnauz  1.89[46]  11 de setembro de 2011  
9        Peter Gould & Gennifer Hutchison  1.80[47]  18 de setembro de 2011  
10            George Mastras & Sam Catlin  1.55[48]  25 de setembro de 2011  
11  Thomas Schnauz & Moira Walley-Beckett  1.73[49]    2 de outubro de 2011  
12                         Vince Gilligan  1.90[50]    9 de outubro de 2011

In [130]:
breaking_bad_temporada_4.columns

Index(['Nº', 'Nº.1', 'Título', 'Dirigido por:', 'Escrito por:', 'Audiência',
       'Exibição Original'],
      dtype='object')

In [131]:
breaking_bad_temporada_4.titulo

0            Box Cutter
1     Thirty-Eight Snub
2            Open House
3         Bullet Points
4               Shotgun
5              Cornered
6           Problem Dog
7              Hermanos
8                   Bug
9                 Salud
10          Crawl Space
11            End Times
12             Face Off
Name: Título, dtype: object

In [132]:
breaking_bad_temporada_4["direcao"]

0        Adam Bernstein
1     Michelle MacLaren
2           David Slade
3         Colin Bucksey
4     Michelle MacLaren
5        Michael Slovis
6           Peter Gould
7           Johan Renck
8       Terry McDonough
9     Michelle MacLaren
10         Scott Winant
11       Vince Gilligan
12       Vince Gilligan
Name: Dirigido por:, dtype: object

In [133]:
DataFrame(breaking_bad_temporada_4, columns=["titulo", "audiencia"])

Título Audiência
0          Box Cutter  2.58[38]
1   Thirty-Eight Snub  1.97[39]
2          Open House  1.71[40]
3       Bullet Points  1.83[41]
4             Shotgun  1.75[42]
5            Cornered  1.67[43]
6         Problem Dog  1.91[44]
7            Hermanos  1.98[45]
8                 Bug  1.89[46]
9               Salud  1.80[47]
10        Crawl Space  1.55[48]
11          End Times  1.73[49]
12           Face Off  1.90[50]

In [134]:
breaking_bad_temporada_4.head(3)

Nº  Nº.1             Título      Dirigido por:    Escrito por: Audiência  \
0  34     1         Box Cutter     Adam Bernstein  Vince Gilligan  2.58[38]   
1  35     2  Thirty-Eight Snub  Michelle MacLaren  George Mastras  1.97[39]   
2  36     3         Open House        David Slade      Sam Catlin  1.71[40]   

     Exibição Original  
0  17 de julho de 2011  
1  24 de julho de 2011  
2  31 de julho de 2011

In [135]:
breaking_bad_temporada_4.tail(2)

Nº  Nº.1     Título   Dirigido por:  \
11  45    12  End Times  Vince Gilligan   
12  46    13   Face Off  Vince Gilligan   

                             Escrito por: Audiência     Exibição Original  
11  Thomas Schnauz & Moira Walley-Beckett  1.73[49]  2 de outubro de 2011  
12                         Vince Gilligan  1.90[50]  9 de outubro de 2011

In [136]:
breaking_bad_temporada_4.loc[0]

Nº                                    34
Nº.1                                   1
Título                        Box Cutter
Dirigido por:             Adam Bernstein
Escrito por:              Vince Gilligan
Audiência                       2.58[38]
Exibição Original    17 de julho de 2011
Name: 0, dtype: object

In [137]:
breaking_bad_temporada_4["pais"]="Estados Unidos"
breaking_bad_temporada_4

Nº  Nº.1             Título      Dirigido por:  \
0   34     1         Box Cutter     Adam Bernstein   
1   35     2  Thirty-Eight Snub  Michelle MacLaren   
2   36     3         Open House        David Slade   
3   37     4      Bullet Points      Colin Bucksey   
4   38     5            Shotgun  Michelle MacLaren   
5   39     6           Cornered     Michael Slovis   
6   40     7        Problem Dog        Peter Gould   
7   41     8           Hermanos        Johan Renck   
8   42     9                Bug    Terry McDonough   
9   43    10              Salud  Michelle MacLaren   
10  44    11        Crawl Space       Scott Winant   
11  45    12          End Times     Vince Gilligan   
12  46    13           Face Off     Vince Gilligan   

                             Escrito por: Audiência       Exibição Original  \
0                          Vince Gilligan  2.58[38]     17 de julho de 2011   
1                          George Mastras  1.97[39]     24 de julho de 2011   
2                              Sam Catlin  1.71[40]     31 de julho de 2011   
3                    Moira Walley-Beckett  1.83[41]     7 de agosto de 2011   
4                          Thomas Schnauz  1.75[42]    14 de agosto de 2011   
5                      Gennifer Hutchison  1.67[43]    21 de agosto de 2011   
6                             Peter Gould  1.91[44]    28 de agosto de 2011   
7             Sam Catlin & George Mastras  1.98[45]   4 de setembro de 2011   
8   Moira Walley-Beckett & Thomas Schnauz  1.89[46]  11 de setembro de 2011   
9        Peter Gould & Gennifer Hutchison  1.80[47]  18 de setembro de 2011   
10            George Mastras & Sam Catlin  1.55[48]  25 de setembro de 2011   
11  Thomas Schnauz & Moira Walley-Beckett  1.73[49]    2 de outubro de 2011   
12                         Vince Gilligan  1.90[50]    9 de outubro de 2011   

              País  
0   Estados Unidos  
1   Estados Unidos  
2   Estados Unidos  
3   Estados Unidos  
4   Estados Unidos  
5   Estados Unidos  
6   Estados Unidos  
7   Estados Unidos  
8   Estados Unidos  
9   Estados Unidos  
10  Estados Unidos  
11  Estados Unidos  
12  Estados Unidos

In [138]:
breaking_bad_temporada_4["pais"] = "Estados Unidos"
breaking_bad_temporada_4["Contador"] = np.arange(13)
breaking_bad_temporada_4

Nº  Nº.1             Título      Dirigido por:  \
0   34     1         Box Cutter     Adam Bernstein   
1   35     2  Thirty-Eight Snub  Michelle MacLaren   
2   36     3         Open House        David Slade   
3   37     4      Bullet Points      Colin Bucksey   
4   38     5            Shotgun  Michelle MacLaren   
5   39     6           Cornered     Michael Slovis   
6   40     7        Problem Dog        Peter Gould   
7   41     8           Hermanos        Johan Renck   
8   42     9                Bug    Terry McDonough   
9   43    10              Salud  Michelle MacLaren   
10  44    11        Crawl Space       Scott Winant   
11  45    12          End Times     Vince Gilligan   
12  46    13           Face Off     Vince Gilligan   

                             Escrito por: Audiência       Exibição Original  \
0                          Vince Gilligan  2.58[38]     17 de julho de 2011   
1                          George Mastras  1.97[39]     24 de julho de 2011   
2                              Sam Catlin  1.71[40]     31 de julho de 2011   
3                    Moira Walley-Beckett  1.83[41]     7 de agosto de 2011   
4                          Thomas Schnauz  1.75[42]    14 de agosto de 2011   
5                      Gennifer Hutchison  1.67[43]    21 de agosto de 2011   
6                             Peter Gould  1.91[44]    28 de agosto de 2011   
7             Sam Catlin & George Mastras  1.98[45]   4 de setembro de 2011   
8   Moira Walley-Beckett & Thomas Schnauz  1.89[46]  11 de setembro de 2011   
9        Peter Gould & Gennifer Hutchison  1.80[47]  18 de setembro de 2011   
10            George Mastras & Sam Catlin  1.55[48]  25 de setembro de 2011   
11  Thomas Schnauz & Moira Walley-Beckett  1.73[49]    2 de outubro de 2011   
12                         Vince Gilligan  1.90[50]    9 de outubro de 2011   

              País  Contador  
0   Estados Unidos         0  
1   Estados Unidos         1  
2   Estados Unidos         2  
3   Estados Unidos         3  
4   Estados Unidos         4  
5   Estados Unidos         5  
6   Estados Unidos         6  
7   Estados Unidos         7  
8   Estados Unidos         8  
9   Estados Unidos         9  
10  Estados Unidos        10  
11  Estados Unidos        11  
12  Estados Unidos        12

Convertendo um dicionário em Dataframe

In [139]:
dict_cidade = {"Cidade":["Santo André", "São Paulo", "São José dos Campos"], "Estado":["SP", "SP", "SP"]} 
dict_cidade

{'Cidade': ['Santo André', 'São Paulo', 'São José dos Campos'],
 'Estado': ['SP', 'SP', 'SP']}

In [140]:
df_cidade = DataFrame(dict_cidade)
df_cidade

Cidade Estado
0          Santo André     SP
1            São Paulo     SP
2  São José dos Campos     SP

### Reindexing

In [141]:
serie_1 = Series([1,2,3,4,5], index = ["a", "b", "c", "d", "e"])
serie_1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [142]:
serie_2 = serie_1.reindex( ["a", "b", "c", "d", "e", "f", "g", "h"])
serie_2

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64

In [143]:
serie_2 = serie_1.reindex( ["a", "b", "c", "d", "e", "f", "g", "h"], fill_value=0)
serie_2

a    1
b    2
c    3
d    4
e    5
f    0
g    0
h    0
dtype: int64

In [144]:
serie_3 = Series(["Santa Catarina", "Santo André", "Santo Antônio"], index = [0, 5, 8])
serie_3

0    Santa Catarina
5       Santo André
8     Santo Antônio
dtype: object

In [145]:
index_range = range(15)
index_range

range(0, 15)

Documentação do Reindex
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.reindex.html

O method tem as seguintes possibilidades:

method : {None, ‘backfill’/’bfill’, ‘pad’/’ffill’, ‘nearest’}, optional

method to use for filling holes in reindexed DataFrame. Please note: this is only applicable to DataFrames/Series with a monotonically increasing/decreasing index.

* default: don’t fill gaps
* pad / ffill: propagate last valid observation forward to next valid
* backfill / bfill: use next valid observation to fill gap
* nearest: use nearest valid observations to fill gap

In [146]:
serie_4 = serie_3.reindex(index_range, method="ffill")
serie_4

0     Santa Catarina
1     Santa Catarina
2     Santa Catarina
3     Santa Catarina
4     Santa Catarina
5        Santo André
6        Santo André
7        Santo André
8      Santo Antônio
9      Santo Antônio
10     Santo Antônio
11     Santo Antônio
12     Santo Antônio
13     Santo Antônio
14     Santo Antônio
dtype: object

In [147]:
serie_4 = serie_3.reindex(index_range, method="bfill")
serie_4

0     Santa Catarina
1        Santo André
2        Santo André
3        Santo André
4        Santo André
5        Santo André
6      Santo Antônio
7      Santo Antônio
8      Santo Antônio
9                NaN
10               NaN
11               NaN
12               NaN
13               NaN
14               NaN
dtype: object

In [148]:
serie_4 = serie_3.reindex(index_range, method="nearest")
serie_4

0     Santa Catarina
1     Santa Catarina
2     Santa Catarina
3        Santo André
4        Santo André
5        Santo André
6        Santo André
7      Santo Antônio
8      Santo Antônio
9      Santo Antônio
10     Santo Antônio
11     Santo Antônio
12     Santo Antônio
13     Santo Antônio
14     Santo Antônio
dtype: object

Utilizando em Dataframes

In [152]:
data_frame = DataFrame(np.random.randn(25).reshape((5,5)), 
          index=["a", "b", "d", "e", "f"], 
          columns=["col_1", "col_2", "col_3", "col_4", "col_5"])
data_frame

col_1     col_2     col_3     col_4     col_5
a  0.983838 -1.437066  1.773980  1.154571 -1.936825
b  1.521577 -0.445587 -1.297115  0.115884  0.025427
d  2.453676 -2.187166  0.521424 -1.384558  0.948770
e  0.052354  1.846954  0.921501 -0.035536  0.129741
f  1.223859 -0.879815 -0.967171 -2.257573 -0.523790

In [150]:
data_frame_2 = data_frame.reindex(index=["a", "b", "c", "d", "e", "f"], method="ffill")
data_frame_2

col_1     col_2     col_3     col_4     col_5
a  0.008827 -0.138637 -1.031740 -0.485992  2.490055
b  0.348574 -0.882852 -0.180926  0.311109  0.774995
c  0.348574 -0.882852 -0.180926  0.311109  0.774995
d -1.341370  0.643482  1.504623  0.211559  0.141409
e  0.136749  0.644035 -2.363881  0.268204 -1.843185
f -0.655100 -0.598666 -1.281287 -0.588305 -1.819364

In [151]:
data_frame_2 = data_frame_2.reindex(columns=["col_1", "col_2", "col_3", "col_4", "col_5", "col_6"], fill_value=5)
data_frame_2

col_1     col_2     col_3     col_4     col_5  col_6
a  0.008827 -0.138637 -1.031740 -0.485992  2.490055      5
b  0.348574 -0.882852 -0.180926  0.311109  0.774995      5
c  0.348574 -0.882852 -0.180926  0.311109  0.774995      5
d -1.341370  0.643482  1.504623  0.211559  0.141409      5
e  0.136749  0.644035 -2.363881  0.268204 -1.843185      5
f -0.655100 -0.598666 -1.281287 -0.588305 -1.819364      5