## Desafio 1
___

Supondo que uma imagem é composta por uma matriz 4 x 4, mapeie as letras a, d e j conforme a figura abaixo, sendo a cor cinza representada pelo bit 1 e a branca pelo bit 0.

Hint: para inicializar as matrizes opte pelas estruturas np.ones e np.zeros e utilize *slice notation*.

<img src="challenge1.png">

In [2]:
import numpy as np

In [40]:
def letra_a():
    letra = np.zeros([4,4])
    
    letra[1:4, 0] = 1

    letra[0,1] = 1 
    letra[2,1] = 1 

    letra[0,2] = 1 
    letra[2,2] = 1 
    
    letra[1:4, 3] = 1
        
    return letra

In [41]:
def letra_d():
    letra = np.zeros([4,4])

    letra[:, 0] = 1

    letra[0,1] = 1 
    letra[3,1] = 1 

    letra[0,2] = 1 
    letra[3,2] = 1 

    letra[1,3] = 1 
    letra[2,3] = 1 
    
    return letra

In [45]:
def letra_j():
    letra = np.zeros([4,4])

    letra[0,0] = 1 
    letra[2,0] = 1 
    letra[3,0] = 1 
    
    letra[0,1] = 1 
    letra[3,1] = 1 

    letra[:, 2] = 1

    letra[0,3] = 1 

    return letra

In [46]:
letra_a()

array([[ 0.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  1.]])

In [47]:
letra_d()

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  0.]])

In [48]:
letra_j()

array([[ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.],
       [ 1.,  0.,  1.,  0.],
       [ 1.,  1.,  1.,  0.]])